---
title: "[`gradientcobra v1.0.6`](https://pypi.org/project/gradientcobra/) package"
author: "[`Sothea HAS`](https://hassothea.github.io/)"
format: 
    html:
        anchor-sections: true
        code-tools: true
toc: true
toc-depth: 3
jupyter: python3
---

# Installing and importing packages

[gradientcobra](https://pypi.org/project/gradientcobra/) can be installed from [pypi](https://pypi.org/) using `pip`:

> ``pip install gradientcobra``

The package contains the following methods:

# [Gradient COBRA](https://hassothea.github.io/files/CodesPhD/GradientCOBRA.html)

**Gradient COBAR** is a kernel-based consensual aggregation method for regressoin ([S. Has (2023)](https://jdssv.org/index.php/jdssv/article/view/70)). After installing [`gradientcobra`](https://pypi.org/project/gradientcobra/) package (version $\geq$ `v1.0.6`), `GradientCOBRA` method can be imported by:

> ``from gradientcobra.gradientcobra import GradientCOBRA``

For more information about this method, read [GradientCOBRA documentation](https://hassothea.github.io/files/CodesPhD/GradientCOBRA.html).

# [MixCOBRARegressor](https://hassothea.github.io/files/CodesPhD/MixCOBRARegressor.html)

**MixCOBRA** is an aggregation method for both regression and classification that takes into account both input and output of the basic estimators ([A. Fischer and M. Mougeot (2019)](https://www.sciencedirect.com/science/article/pii/S0378375818302349)). From `version 1.0.5`, this method is also available for regression and can be implemented in python by:

> ``from gradientcobra.mixcobra import MixCOBRARegressor``

A challenge of this method is that it has to be optimized over a $2$D-grid of parameters $(\alpha, \beta)$ for input and output part. In `gradientcobra` library, the implementation of this method is optimized so that it works very efficiently. Moreover, you can also use gradient descent algorithm to estimate the parameters $(\alpha, \beta)$, or only one bandwidth parameter $h$ can be used for both input and output part. For more information on how to use this method, read [MixCOBRARegressor documentation](https://hassothea.github.io/files/CodesPhD/MixCOBRARegressor.html).


# References

-  [S. Has (2023). A Gradient COBRA: A kernel-based consensual aggregation for regression. Journal of Data Science, Statistics, and Visualisation, 3(2).](https://jdssv.org/index.php/jdssv/article/view/70)
-  [A. Fischer, M. Mougeot (2019). Aggregation using input-output trade-off. Journal of Statistical Planning and Inference, 200.](https://www.sciencedirect.com/science/article/pii/S0378375818302349)
-  [G. Biau, A. Fischer, B. Guedj and J. D. Malley (2016), COBRA: A combined regression strategy, Journal of Multivariate Analysis.](https://doi.org/10.1016/j.jmva.2015.04.007)
-  [M. Mojirsheibani (1999), Combining Classifiers via Discretization, Journal of the American Statistical Association.](https://www.jstor.org/stable/2670180)



